name: Docker Image CI

on: []

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACHYDERM_CLUSTER_URL: ${{ secrets.PACHYDERM_URL }}
      PACHYDERM_TOKEN: ${{ secrets.PACHYDERM_TOKEN }}
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE }}
      PACHYDERM_PIPELINE_FILES: <list pipeline JSON files here>
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_TOKEN }}' | docker login --username '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin
      - name: Build the tagged Docker image
        run: docker build --tag ${DOCKER_IMAGE_NAME}:${GITHUB_SHA} .
      - name: Push docker image
        run: docker push ${DOCKER_IMAGE_NAME}:${GITHUB_SHA}
      - name: pachyderm-update-pipelines
        uses: /pachdyerm-pipeline-action/.
        id: pup
